### PR TITLE
Adding private token argument.

### PR DESCRIPTION
**Pull request by marcelomarra**
If you are using Gitlab CI templates, you need to provide a private token in order to gitlab validate the full chain of templates.

Let me know what you guys think.

### CODE REVIEW

**Comment by marcelomarra** [comment]
@pradel

**Comment by pradel** [comment]
I don't use this feature of gitlab, so I trust you it's working :)
Can you just rename the option `--private_token` to `--private-token` please?
Can you paste a screenshot of your change to the error messages?

Thanks for the pr!

**Comment by marcelomarra** [comment]
Message if you don't use the private-token option:
image

Message if you use a valid private-token:
image

Message if you use an invalid private-token:
image

Message if your private-token has a different scope:
image

**Comment by marcelomarra** [comment]
@pradel I've added the changes as requested.

Cheers!

**Comment by pradel** [comment]
Thanks @marcelomarra published as v0.3.O 🚀

**Pull request merged**
